apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: primary-ingress
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        backend:
          serviceName: rollouts-demo
          servicePort: 80
      - path: /canarypath
        backend:
          serviceName: canary-service
          servicePort: 80
      - path: /stablepath
        backend:
          serviceName: stable-service
          servicePort: 80
